#!/bin/bash
echo "<!-- Generated by: Lots of libs loader creator by TStudios. -->" > lotsoflibs.html
echo -e "<!-- CSS -->" >> lotsoflibs.html
if [[ -f "${HOME}/.klsh/.klshcore" ]]; then
	source $HOME/.klsh/.klshcore -s
fi
i=0
function css {
  echo -e "${green}C${blue}S${red}S${black}-${resetall}Progress:"
  x=$(cat $HOME/lotsoflibs/css.list)
  rm -rf $PWD/css
  mkdir $PWD/css
  cd $PWD/css
  while read line; do
    y=`basename $line`
    echo -e "${blue}Downloading ${red}$y ${yellow}(Source: $line)"
    wget -O $y --quiet $line
    echo -e "${green}Finished ${resetall}${inverted}Downloading${resetall} ${red}$y."
    echo -e "${green}Adding ${red}$y${green} to ${red}lotsoflibs.html"
    echo -e "<!-- $y   SOURCE: $line -->\n<style>" >> ../lotsoflibs.html
    cat ./$y  >> ../lotsoflibs.html
    echo "</style>" >> ../lotsoflibs.html
    echo "${green}Added ${red}$y ${green}to ${red}lotsoflibs.html"
    ((i++))
  done <<< "$x"
  cd ..
}
echo -e "\n\n<!-- JS -->" >> lotsoflibs.html
function js {
  echo -e "${red}J${green}S${black}-${resetall}Progress:"
  x=$(cat $HOME/lotsoflibs/js.list)
  rm -rf $PWD/js
  mkdir $PWD/js
  cd $PWD/js
  while read line; do
    y=`basename $line`
    echo -e "${blue}Downloading ${red}$y ${yellow}(Source: $line)"
    wget -O $y --quiet $line
    echo -e "${green}Finished ${resetall}${inverted}Downloading${resetall} ${red}$y."
    echo -e "${green}Adding ${red}$y${green} to ${red}lotsoflibs.html"
    echo -e "<!-- $y   SOURCE: $line -->\n<script>" >> ../lotsoflibs.html
    cat ./$y  >> ../lotsoflibs.html
    echo "</script>" >> ../lotsoflibs.html
    echo "${green}Added ${red}$y ${green}to ${red}lotsoflibs.html"
    ((i++))
  done <<< "$x"
  cd ..
}
js
echo -e "\n\n"
css
echo -e "\n\n\n${green}Loaded ${blue}$i ${green}Libraries into ${blue}$PWD/lotsoflibs.html"
