#!/bin/bash
echo "<!-- Generated by: Lots of libs loader creator by TStudios. -->" > lotsoflibs.html
echo -e "<!-- CSS -->" >> lotsoflibs.html
i=0
function css {
  x=$(cat css.list)
  rm -rf css
  mkdir css
  cd css
  while read line; do
    y=`basename $line`
    wget -O $y --quiet $line
    echo -e "<!-- $y   SOURCE: $line -->\n<style>" >> ../lotsoflibs.html
    cat ./$y  >> ../lotsoflibs.html
    echo "</style>" >> ../lotsoflibs.html
    ((i++))
  done <<< "$x"
  cd ..
}
css
echo -e "\n\n<!-- JS -->" >> lotsoflibs.html
function js {
  x=$(cat js.list)
  rm -rf js
  mkdir js
  cd js
  while read line; do
    y=`basename $line`
    wget -O $y --quiet $line
    echo -e "<!-- $y   SOURCE: $line -->\n<script>" >> ../lotsoflibs.html
    cat ./$y  >> ../lotsoflibs.html
    echo "</script>" >> ../lotsoflibs.html
    ((i++))
  done <<< "$x"
  cd ..
}
js
